Name: Execute GitVersion
Description: This action executes gitversion with a custom config file to specify certain options
author: harmandersihra

outputs:
  major:
    value: ${{ steps.gitversion.outputs.major }}
  minor:
    value: ${{ steps.gitversion.outputs.minor }}
  patch:
    value: ${{ steps.gitversion.outputs.patch }}
  fullSemVer:
    value: ${{ steps.gitversion.outputs.fullSemVer }}
  buildMetaData:
    value: ${{ steps.gitversion.outputs.BuildMetaData }}

runs:
  using: composite
  steps:
    - id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true
        configFilePath: ${{ github.action_path }}\GitVersion.yml
