Name: Write Build Version
description: This writes the semver info taken in as an input to the BuildVersion.h file in the project
author: harmandersihra

inputs:
  major_version:
    description: The Major version
    required: true
  minor_version:
    description: The Minor version
    required: true
  patch_version:
    description: The Patch version
    required: true
    
runs:
  using: composite
  steps:
    - run: python script.py ${{inputs.major_version}} ${{inputs.minor_version}} ${{inputs.patch_version}}
      shell: bash
