name: Collect Release Artifacts
description: This action collects release artifacts in a folder and appends the version to their name.
author: willson556

inputs:
  version:
    description: The Major version
    required: true
  artifacts:
    description: comma-separated globbing patterns for artifacts to collect
    required: true
  destination:
    description: destination folder for the artifacts
    required: false
    default: release

    
runs:
  using: composite
  steps:
    - run: python3 ${GITHUB_ACTION_PATH}/script.py "${{ inputs.version }}" "${{inputs.artifacts}}" "${{ inputs.destination }}"
      shell: bash
