Name: Write Build Version
description: This writes the semver info taken in as an input to the BuildVersion.h file in the project
author: harmandersihra

inputs:
  filepath:
    description: BuildVersion.h path
    required: true
  major_version:
    description: The Major version
    required: true
  minor_version:
    description: The Minor version
    required: true
  patch_version:
    description: The Patch version
    required: true
  pre_release_tag:
    description: The pre-release tag
    required: true
  pre_release_number:
    description: The pre-release number
    required: true
    
runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}\script.py ${{inputs.filepath}} ${{inputs.major_version}} ${{inputs.minor_version}} ${{inputs.patch_version}} ${{inputs.pre_release_tag}} ${{inputs.pre_release_number}}
      shell: powershell
      if: runner.os != 'Linux'
    - run: ls -al ${GITHUB_ACTION_PATH}
      shell: bash
      if: runner.os == 'Linux'
    - run: python3 ${GITHUB_ACTION_PATH}/script.py ${{inputs.filepath}} ${GITVERSION_MAJOR} ${GITVERSION_MINOR} ${GITVERSION_PATCH} ${GITVERSION_PRERELEASETAG} ${GITVERSION_PRERELEASENUMBER}
      if: runner.os == 'Linux'
      shell: bash
