name: AssignReviewers tests

on:
  pull_request:
    paths: [AssignReviewers/**, ReviewConfig/**]
  push:
    branches: [main]
    paths: [AssignReviewers/**, ReviewConfig/**]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: node --test AssignReviewers/ ReviewConfig/
