name: Basic Build

on:
  workflow_call:
    inputs:
      project_name:
        description: This is the name of the project being built
        required: true
        type: string
      build_config:
        description: These are the build configs you want to build in CCStudio. Make this a comma separated list e.g. "Debug,Heartbeat_Disabled"
        required: true
        type: string
      clean_workspace:
        description: Set to true if the workspace should be cleaned when this completes. Set to false if you have more to do.
        required: false
        type: boolean
        default: true 
      build_version_path:
        default: BuildVersion.h
        type: string
      run-format:
        required: False
        default: True
        type: boolean
      format-exclude:
        default: ''
        type: string
      increment-build:
        required: false
        type: boolean
        default: true
    outputs:
      tag_version:
        description: version number of tag
        value: ${{ jobs.build.outputs.tag_version }}

    secrets:
      STAFL_CI_PRIVATE_KEY:
        required: true
        description: access token for dependency checking

jobs:
  format:
    if: ${{ inputs.run-format }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.2
    - uses: DoozyX/clang-format-lint-action@v0.17
      with:
        source: '.'
        exclude: ${{ inputs.format-exclude }}
        extensions: 'h,cpp'
        clangFormatVersion: 14
    
  build:
    runs-on: ccs
    outputs:
      tag_version: ${{steps.staflversion.outputs.major}}
        
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.1.2
      with:
        fetch-depth: 0

    - name: Fetch tags
      run: git fetch --tags
      
    - name: Checkout Submodules
      shell: cmd
      run: git submodule update --init --recursive

    - name: Determine Version
      if: ${{ inputs.increment-build }}
      id: staflversion
      uses: StaflSystems/CustomGithubActions/DetermineVersion@v4.0.1

    - name: Display SemVer
      if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/dev')
      run: |
        echo "Version: ${{steps.staflversion.outputs.full}}"
    
    - name: Update BuildVersion.h
      uses: StaflSystems/CustomGithubActions/WriteBuildVersion@v4.0.1
      with:
        filepath: ${{inputs.build_version_path}}
        major_version: ${{steps.staflversion.outputs.major}}
        minor_version: ${{steps.staflversion.outputs.minor}}
        patch_version: ${{steps.staflversion.outputs.patch}}
        build_version: ${{steps.staflversion.outputs.build}}
        
    - name: Build Project
      uses: StaflSystems/CustomGithubActions/CCStudioBuild@v4.0.1
      with:
        project_name: ${{ inputs.project_name }}
        build_config: ${{ inputs.build_config }}

    - name: Collect Release Artifacts
      uses: StaflSystems/CustomGithubActions/CollectReleaseArtifacts@v4.0.1
      with:
        version: ${{steps.staflversion.outputs.full}}
        artifacts: "*/*.bin,*/*.out,**/*.dbc,release-artifacts/*"
        destination: "release-artifacts-renamed"

    - name: Create a GitHub release
      if: github.ref == 'refs/heads/main'
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: "release-artifacts-renamed/*"
        tag: ${{steps.staflversion.outputs.full}}
        
    - name: Clean workspace
      uses: mickem/clean-after-action@v2.0.0
      if: ${{ failure() || inputs.clean_workspace }}
