name: CIMetrics tests

on:
  pull_request:
    paths: [CIMetrics/**]
  push:
    branches: [main]
    paths: [CIMetrics/**]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
      - uses: astral-sh/setup-uv@v6
      - run: uv run --no-project --with pytest pytest CIMetrics
